spring:
  application:
    name: JPA Inheritance - Mapped Supperclass
  # Datasource configuration
  datasource:
    url: jdbc:mysql://localhost:3306/inheritance?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false
    name: MySQL Connection
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    # JPA configuration
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show_sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.format_sql: true
springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /v3/api-docs
  # swagger-ui custom path
  swagger-ui:
    path: swagger-ui
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  group-configs:
    - group: inheritance
      paths-to-match: /**
application-description: '@project.description@'
application-version=: "@project.version@"
